### ISSUE TITLE
pangolin::GlFont comilation issue

### ISSUE THREAD

**Issue by bpwiselybabu** [arpg/SceneGraph#14]
The latest current build pangolin::GlFont does not have a default constructor so the build fails. 
The functionality for default font is available as static pangolin::GlFont::I(). The fix it is available at https://github.com/bpwiselybabu/SceneGraph/commit/8066a556f367c3be6e3a322df861f9c8d09e30ef

**Comment by crheckman** [comment]
This should now be resolved in f9958b8f508cb4a3a0574bb609b3dfcc8a92cab2. Thank you!
