### ISSUE TITLE
feature/new_pangolin has no make install target

### ISSUE THREAD

**Issue by JStech** [arpg/SceneGraph#15]
Title says it all. Is there some other install method I should use?

**Comment by crheckman** [comment]
`feature/new_pangolin` has CMake exports on by default for simplicity with Toyota (they don't use installs). 

To fix this on your machine, you need to disable exporting the package. Steps are:

1) Blow away your build dir
2) Run `cmake [path-to-source] -DEXPORT_SceneGraph=OFF`
3) `make install`

That will fix it, but let me know in slack if you are running in to any other kinds of build issues when you try this.
