### ISSUE TITLE
Not able to view texture for the 3DS files

### ISSUE THREAD

**Issue by bpwiselybabu** [arpg/SceneGraph#16]
Hi,

   I ran the modelViewer example on the chair.3DS. The mesh loads but there is no color or texture information loaded. 

   When I open chair.3DS in meshlab the material information is available. I tried it on a couple of other .3DS meshes and have same issue. Is using another format better or is there a bug?

Thanks,
benzun

**Comment by bpwiselybabu** [comment]
I think the location provided for loading the texture png is wrong. Is there anyway for it to append the texture path by the root folder location?

**Comment by crheckman** [comment]
Hi Benzun,

I am looking into this right now. Could you specify where in the code you think the bug is? I have tried loading a couple 3DS files with textured meshes and they also fail to load the textures, so I would like to track this down.

**Comment by bpwiselybabu** [comment]
Hi,

   If I move the texture png files to the folder in which the binary is located textures are loaded, so I suspect that the path names are not getting correctly parsed.

   If you look at function LoadMaterialsTexture( line 375) in GLMesh.cpp. It gets the path name for the texture .png files. This path name does not contain the root folder in which the texture is stored. I dont know what assimp specification for the path name is but prefixing this path name with the root folder location solves the problem for me on my computer.

Thanks,
Benzun

**Comment by crheckman** [comment]
This is a bit challenging to address without pulling in some boost dependencies. Nonetheless, I'm still hacking away at it. Have you been able to solve the problem without pulling in the boost filesystem tools?

**Comment by crheckman** [comment]
Hi Benzun, I've developed a fix that works for me in fix/texture_loading. Could you please test it?

**Comment by bpwiselybabu** [comment]
@crheckman I can confirm that the textures are being loaded correctly based on the fix/texture_loading. Thanks!
