### ISSUE TITLE
Compiling on Windows

### ISSUE THREAD

**Issue by bpwiselybabu** [arpg/SceneGraph#18]
Hi,
    I wanted to compile the scenegraph library on windows. I hit with a problem where it requires SceneGraph/scenegraph_export.h  which I cant seem to find. Any help on how I should go about it?

Thanks,
Benzun

**Comment by sinaaghli** [comment]
Hello Benzun,
thanks for checking out SceneGraph. SceneGraph doesn't support windows sadly, it only supports mac and linux. it seems some one has been trying to add DLL exports but it has not been fully implemented.

Sina,

**Comment by bpwiselybabu** [comment]
Hi Sina,

    I was able to compile the project on windows, though it is not a clean solution. There might be a need to do use ExternalProjectAdd to compile dependencies for scenegraph. The install mechanisms might need to be updated. I will post my fixes once I have my version stable on windows. I am using MSVC 2014.

Thanks,
Benzun

**Comment by sinaaghli** [comment]
Thats great Benzun, If you could also document the steps that one needs to take in order to install Scenegraph on windows that would be great. 
if you post the documentation here I can link your post in our [documentation](https://github.com/arpg/Documentation) repo.
